# SonarQube Project Configuration
sonar.projectKey=bayupur-portofolio-be
sonar.projectName=Bayupur Portfolio BE
sonar.projectVersion=1.0.0

# Path to the source directories
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,tmp/**,scratch/**,.git/**,.github/**,docker/**

# Code quality settings
sonar.sourceEncoding=UTF-8
sonar.language=go

# Analysis parameters
sonar.scm.provider=git
sonar.scm.disabled=false
