# SonarQube Project Configuration
sonar.projectKey=bayupur-portofolio-be
sonar.projectName=Bayupur Portfolio BE
sonar.projectVersion=1.0.0

# Path to the source and test directories
sonar.sources=cmd,internal,pkg
sonar.tests=tests,internal,pkg
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,tmp/**,scratch/**,**/*.exe,coverage.out
sonar.coverage.exclusions=cmd/**,internal/database/**,internal/bootstrap/**,internal/repository/**
sonar.go.coverage.reportPaths=coverage.out

# Code quality settings
sonar.sourceEncoding=UTF-8
sonar.language=go

# Analysis parameters
sonar.scm.provider=git
sonar.scm.disabled=false
